on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  tests:
    name: CI Tests
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm install
      - name: Lint & Sanity Checks
        run: |
          npm run build:deps
          npm run lint
      - name: Tests
        run: |
          npm run test
      - name: Benchmarks
        run: |
          npm run benchmark
        # only run on pull requests
        if: github.event_name == 'pull_request'
