on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  tests:
    name: CI Tests
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="~/.bun/bin:$PATH"
          bun install
      - name: Lint & Sanity Checks
        run: |
          bun lint
          bun build:deps
          bun x tsc --noEmit
      - name: Tests
        run: |
          bun test
      - name: Benchmarks
        run: |
          bun benchmark
        # only run on pull requests
        if: github.event_name == 'pull_request'
